
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Freifunk Berlin Service-Registrar
LUCI_EXTRA_DEPENDS:=falter-berlin-service-registrar (>=0)
LUCI_PKGARCH:=all

include ../include-luci.mk

# call BuildPackage - OpenWrt buildroot signature
