include $(TOPDIR)/rules.mk

LUCI_TITLE:=Freifunk Berlin configuration wizard
LUCI_EXTRA_DEPENDS:=luci-compat, luci-mod-admin-full, falter-policyrouting, luci-lib-jsonc, falter-profiles, luci-lib-ipkg
PKG_RELEASE:=5

include ../include-luci.mk

#  URL:=http://berlin.freifunk.net

# call BuildPackage - OpenWrt buildroot signature
