include $(TOPDIR)/rules.mk

LUCI_TITLE:=Freifunk Berlin configuration wizard
LUCI_EXTRA_DEPENDS:=luci-compat (>=0), luci-mod-admin-full (>=0), falter-policyrouting (>=0), luci-lib-jsonc (>=0), falter-profiles (>=0), luci-lib-ipkg (>=0)
PKG_RELEASE:=7

include ../include-luci.mk

#  URL:=http://berlin.freifunk.net

# call BuildPackage - OpenWrt buildroot signature
