
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI App for ffwizard3
LUCI_EXTRA_DEPENDS:=falter-berlin-ffwizard3
LUCI_PKGARCH:=all

include ../include-luci.mk

# call BuildPackage - OpenWrt buildroot signature
