#!/bin/sh
test -f /etc/crontabs/root || touch /etc/crontabs/root
OWM="/usr/sbin/owm.sh"
SEED="$( dd if=/dev/urandom bs=2 count=1 2>&- | hexdump | if read -r line; then echo "0x${line#* }"; fi )"
MIN1="$((SEED % 29))"
MIN2="$((MIN1 + 30))"
(crontab -l | grep -v "$OWM"; echo "$MIN1,$MIN2 * * * * test -e $OWM && $OWM") | crontab -
