
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Freifunk Berlin Autoupdate
LUCI_DEPENDS:=falter-berlin-autoupdate
LUCI_PKGARCH:=all

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
