
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Freifunk Berlin Autoupdate
LUCI_EXTRA_DEPENDS:=falter-berlin-autoupdate (>=0)
LUCI_PKGARCH:=all

include ../include-luci.mk

# call BuildPackage - OpenWrt buildroot signature
