#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
# Modified 2015 by Freifunk Berlin
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Freifunk Public and Admin LuCI UI
LUCI_EXTRA_DEPENDS:=luci-mod-admin-full (>=0), luci-lib-json (>=0), falter-profiles (>=0), luci-lib-ipkg (>=0), luci-compat (>=0)
PKG_RELEASE:=9

include ../include-luci.mk

# call BuildPackage - OpenWrt buildroot signature
