---
name: devel-workflow

on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:
  build:
    name: ${{ matrix.arch }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        arch:
          - mipsel_24kc
          - aarch64_generic
          - x86_64

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine branch name
        run: |
          BRANCH="${GITHUB_BASE_REF#refs/heads/}"
          echo "Building for $BRANCH"
          echo "BRANCH=$BRANCH" >> "$GITHUB_ENV"

      - name: Determine changed packages
        run: |
          # only detect packages with changes
          PKG_ROOTS=$(find . -name Makefile | \
            grep -v ".*/src/Makefile" | \
            sed -e 's@./\(.*\)/Makefile@\1/@')
          CHANGES=$(git diff --diff-filter=d --name-only "origin/$BRANCH...")

          # shellcheck disable=SC2001
          for ROOT in $PKG_ROOTS; do
            for CHANGE in $CHANGES; do
              if [[ "$CHANGE" == "$ROOT"* ]]; then
                PACKAGES+=$(echo "$ROOT" | sed -e 's@.*/\(.*\)/@\1 @')
                break
              fi
            done
          done

          # fallback to test packages if nothing explicitly changes this is
          # should run if other mechanics in packages.git changed
          PACKAGES="${PACKAGES:-luci-app-falter-owm}"

          echo "Building $PACKAGES"
          echo "PACKAGES=$PACKAGES" >> "$GITHUB_ENV"

      - name: Build
        uses: openwrt/gh-action-sdk@v7
        env:
          ARCH: ${{ matrix.arch }}

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-packages
          path: |
            bin/packages/{{ matrix.arch }}/*.ipk
            bin/packages/{{ matrix.arch }}/*.apk

      - name: Store logs
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.ARCHIVE_NAME}}-logs
          path: |
            logs/

      - name: Remove logs
        run: sudo rm -rf logs/ || true
